version: '3'

services:

  database:
    image: "postgres:15.2-bullseye"
    container_name: database
    volumes:
      - laundry-online-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=laundry-online
      - POSTGRES_USER=laundry-online
      - POSTGRES_PASSWORD=laundry-online
  laundry-online-app:
    build: ./app
    container_name: laundry-online-app
    environment:
      - DB_SERVER=database
      - POSTGRES_DB=laundry-online
      - POSTGRES_USER=laundry-online
      - POSTGRES_PASSWORD=laundry-online
    ports:
      - "8080:8080"
    links:
      - database
  laundry-online-ui:
    build: ./ui
    container_name: laundry-online-ui
    ports:
      - "4200:4200"
    depends_on:
      - laundry-online-app
volumes:
  laundry-online-data: