CREATE SEQUENCE IF NOT EXISTS users_sequence
    INCREMENT 1
    START 1;

CREATE TABLE IF NOT EXISTS users
(
    id BIGINT NOT NULL PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    document VARCHAR(11) UNIQUE NOT NULL,
    phone VARCHAR(20) NOT NULL,
    email VARCHAR(150) NOT NULL,
    password VARCHAR(250) NOT NULL,
    cep VARCHAR(12) NOT NULL,
    street VARCHAR(250) NOT NULL,
    streetNumber VARCHAR(10) NOT NULL,
    district VARCHAR(250) NOT NULL,
    city VARCHAR(250) NOT NULL,
    state CHAR(2) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS clothings_sequence
    INCREMENT 1
    START 1;

CREATE TABLE IF NOT EXISTS clothings
(
    id BIGINT NOT NULL PRIMARY KEY,
    name VARCHAR(250) UNIQUE NOT NULL,
    washPrice FLOAT(10,2) NOT NULL,
    washPrice INTEGER NOT NULL
);